import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fixture} from './fixture.mjs';
import {capturePublishedRelease,validateRelease,activateStoredRelease,retainedReleaseIds} from '../prepare-retained-release.mjs';
import {publishSite} from '../copy-site.mjs';
import {chromium} from './browser.mjs';
const repo=path.resolve(import.meta.dirname,'../../..'),dir=path.resolve(process.env.RELEASE_QA_ROOT||path.join(repo,'.release-qa')),a=path.resolve(process.env.RELEASE_QA_BASELINE||path.join(dir,'baseline-dist')),b=path.join(dir,'B-dist'),output=path.resolve(process.env.RELEASE_QA_OUTPUT||path.join(dir,'release-fixture'));
const evidence={profile:path.join(dir,'g1-profile'),cacheCleared:false,routing:false,checks:[],responses:[],served:[],attemptedOfficial:[],errors:[]};
const check=(name,passed,detail)=>{evidence.checks.push({name,passed,detail});fs.writeFileSync(path.join(dir,'g1.json'),JSON.stringify(evidence,null,2));};
fs.mkdirSync(output,{recursive:true});fs.cpSync(a,output,{recursive:true});const A=capturePublishedRelease(output,'A');const serving=await fixture(output,3023);let context;
const mainTag=html=>html.match(/src="([^"]+\.js)"/)?.[1];
try{
 context=await chromium.launchPersistentContext(evidence.profile,{channel:'chrome',headless:true,ignoreDefaultArgs:['--disable-back-forward-cache'],viewport:{width:1440,height:900},args:['--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1, EXCLUDE localhost']});
 const track=async page=>{await page.addInitScript(()=>{window.pageEvents=[];addEventListener('pageshow',e=>window.pageEvents.push({type:'pageshow',persisted:e.persisted,at:Date.now()}));addEventListener('pagehide',e=>window.pageEvents.push({type:'pagehide',persisted:e.persisted,at:Date.now()}));});page.on('request',req=>{if(req.url().includes('tile.openstreetmap.org'))evidence.attemptedOfficial.push(req.url());});page.on('pageerror',e=>evidence.errors.push(e.message));const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');cdp.on('Network.responseReceived',r=>evidence.responses.push({url:r.response.url,status:r.response.status,headers:r.response.headers,fromDiskCache:r.response.fromDiskCache,fromServiceWorker:r.response.fromServiceWorker}));cdp.on('Network.requestServedFromCache',r=>evidence.served.push(r.requestId));return page;};
 const page=await track(context.pages()[0]||await context.newPage());await page.goto('http://127.0.0.1:3023/our_story/#photos');await page.getByRole('button',{name:'地图查看',exact:true}).waitFor();
 const old=await track(await context.newPage());await old.goto('http://127.0.0.1:3023/our_story/#photos');await old.getByRole('button',{name:'地图查看',exact:true}).waitFor();
 await page.bringToFront();await page.getByRole('button',{name:'地图查看',exact:true}).click();await page.locator('.gallery-map-osm-tiles img').first().waitFor();await page.waitForTimeout(1000);
 const originalTag=mainTag(fs.readFileSync(path.join(a,'index.html'),'utf8'));const bRelease=publishSite(b,output);const B=JSON.parse(fs.readFileSync(path.join(output,'release-manifests',bRelease.id+'.json'),'utf8'));serving.state.release='B';
 const fresh=await old.evaluate(()=>fetch('/our_story/').then(r=>r.text()));check('600s fresh entry remains A',mainTag(fresh)===originalTag,{tag:mainTag(fresh),expected:originalTag});
 await old.bringToFront();await old.getByRole('button',{name:'地图查看',exact:true}).click();await old.locator('.gallery-map-province').first().waitFor();check('old A lazy map after B retains full dependency closure',validateRelease(output,A)&&await old.locator('.gallery-map-osm-tiles img').count()>0,{Afiles:A.files.length,Bfiles:B.files.length});
 // Expire a separate short-TTL URL naturally, then change the same entry at the same origin.
 serving.state.ttl=1;await old.evaluate(()=>fetch('/our_story/index.html').then(r=>r.text()));await old.waitForTimeout(2200);
 const expiry=await old.evaluate(()=>fetch('/our_story/index.html').then(r=>r.text()));const bTag=mainTag(fs.readFileSync(path.join(b,'index.html'),'utf8'));check('entry reaches verifiable B refresh condition',mainTag(expiry)===bTag,{tag:mainTag(expiry),bTag});
 const current=await track(await context.newPage());await current.goto('http://127.0.0.1:3023/our_story/index.html#photos');await current.getByRole('button',{name:'地图查看',exact:true}).waitFor();await current.getByRole('button',{name:'地图查看',exact:true}).click();await current.locator('.gallery-map-osm-tiles img').first().waitFor();await current.waitForTimeout(1200);
 const dataUrls=evidence.responses.filter(r=>/gallery\/versioned\/.*\.json/.test(r.url));check('B actual map data are content-versioned',dataUrls.length>=3,{urls:dataUrls.map(r=>r.url)});
 await current.waitForTimeout(2200);const start=serving.state.requests.length;await current.reload();await current.getByRole('button',{name:'地图查看',exact:true}).click();await current.locator('.gallery-map-osm-tiles img').first().waitFor();await current.waitForTimeout(1500);check('expired synthetic XYZ conditional 304',serving.state.requests.slice(start).some(r=>r.tile&&r.status===304),serving.state.requests.slice(start).filter(r=>r.tile));
 serving.state.tileVersion++;await current.waitForTimeout(2200);const changedAt=serving.state.requests.length;await current.reload();await current.getByRole('button',{name:'地图查看',exact:true}).click();await current.locator('.gallery-map-osm-tiles img').first().waitFor();await current.waitForTimeout(1200);check('changed XYZ representation gets 200 with new ETag',serving.state.requests.slice(changedAt).some(r=>r.tile&&r.conditional&&r.status===200),serving.state.requests.slice(changedAt).filter(r=>r.tile));
 for(let i=0;i<10;i++){await current.getByRole('button',{name:'回到邮册',exact:true}).click();await current.getByRole('button',{name:'地图查看',exact:true}).click();await current.waitForTimeout(50);}await current.getByRole('button',{name:'回到邮册',exact:true}).click();const quietAt=serving.state.requests.length;await current.waitForTimeout(1400);check('ten close/reentry leaves no background XYZ',!serving.state.requests.slice(quietAt).some(r=>r.tile),{requests:serving.state.requests.slice(quietAt)});
 await current.getByRole('button',{name:'地图查看',exact:true}).click();await current.waitForTimeout(400);await current.goto('http://127.0.0.1:3023/away');await current.evaluate(()=>history.back());await current.waitForTimeout(600);const pageEvents=await current.evaluate(()=>window.pageEvents);check('actual BFCache pageshow.persisted',pageEvents.some(e=>e.type==='pageshow'&&e.persisted),pageEvents);
 if(!await current.locator('.gallery-map-stage').count()){await current.getByRole('button',{name:'地图查看',exact:true}).click();await current.locator('.gallery-map-province').first().waitFor();}
 const cdp=await context.newCDPSession(current);await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await current.waitForTimeout(500);check('offline cached map remains interactive with fallback',await current.locator('.gallery-map-province').count()===34,{ready:await current.locator('.gallery-map-osm-tiles').getAttribute('data-ready')});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});await current.getByRole('button',{name:'放大地图',exact:true}).click();await current.waitForTimeout(1200);check('weak network maintains controls',await current.locator('.gallery-map-zoom').isVisible(),{});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
 // C has a detached temporary schema2 data file and its matching compiled parser.
 const cRoot=path.join(dir,'C-source/Cabinet/dist'),cRelease=publishSite(cRoot,output,{sourceRepo:path.join(dir,'C-source')}),C=JSON.parse(fs.readFileSync(path.join(output,'release-manifests',cRelease.id+'.json'),'utf8'));serving.state.release='C';
 const cPage=await track(await context.newPage());await cPage.goto('http://127.0.0.1:3023/our_story/index.html#photos');await cPage.getByRole('button',{name:'地图查看',exact:true}).waitFor();const cAt=serving.state.requests.length;await cPage.getByRole('button',{name:'地图查看',exact:true}).click();await cPage.locator('.gallery-map-province').first().waitFor();
 const cData=JSON.parse(fs.readFileSync(path.join(cRoot,'gallery-resource-manifest.json'),'utf8')).files.find(file=>file.name==='gallery/map/china-4.0.2.json');
 check('C changed content/schema uses new URL and matching parser 200',await cPage.locator('.gallery-map-province').count()===34&&serving.state.requests.slice(cAt).some(r=>r.url.includes(cData.hash)&&r.status===200),{hash:cData.hash,schema:'FixtureGallerySchema2',requests:serving.state.requests.slice(cAt).filter(r=>r.url.includes('json'))});
 check('rapid B/C retains A and B dependency/schema closure',validateRelease(output,A)&&validateRelease(output,B)&&validateRelease(output,C)&&retainedReleaseIds([A,B,C]).length===3,{Cfiles:C.files.length,oldBRegions:await current.locator('.gallery-map-province').count()});
 activateStoredRelease(output,A.id);serving.state.release='A-rollback';await current.waitForTimeout(2200);const rollback=await current.evaluate(()=>fetch('/our_story/index.html').then(r=>r.text()));check('rollback entry A retains B dependency closure',mainTag(rollback)===originalTag&&validateRelease(output,B),{tag:mainTag(rollback)});
 const failed=await track(await context.newPage());await failed.goto('http://127.0.0.1:3023/our_story/index.html#photos');await failed.getByRole('button',{name:'地图查看',exact:true}).waitFor();const mapChunk=A.files.find(f=>/assets\/GalleryMap-.*\.js$/.test(f.path));serving.state.missing.add('/'+mapChunk.path);const faultCdp=await context.newCDPSession(failed);await faultCdp.send('Network.enable');await faultCdp.send('Network.setBlockedURLs',{urls:['*'+mapChunk.path+'*']});await failed.getByRole('button',{name:'地图查看',exact:true}).click();try{await failed.getByRole('heading',{name:'地图暂时没有展开'}).waitFor({timeout:5000});check('blocked old chunk exposes bounded existing recovery',true,{failure:'CDP transfer fault, not server 404 through a populated immutable HTTP cache'});}catch{check('blocked old chunk exposes bounded existing recovery',false,{reason:'cached module prevented transfer fault from being exercised'});}serving.state.missing.clear();await faultCdp.send('Network.setBlockedURLs',{urls:[]});
 check('no official XYZ / no Service Worker',evidence.attemptedOfficial.length===0, {attempted:evidence.attemptedOfficial,workers:await current.evaluate(async()=>({controller:!!navigator.serviceWorker.controller,registrations:(await navigator.serviceWorker.getRegistrations()).length}))});
 const dRoot=path.join(dir,'D-source/Cabinet/dist');
 const dRelease=publishSite(dRoot,output,{sourceRepo:path.join(dir,'D-source')}),D=JSON.parse(fs.readFileSync(path.join(output,'release-manifests',dRelease.id+'.json'),'utf8'));serving.state.release='D';
 const lazyD=await track(await context.newPage());await lazyD.addInitScript(()=>Object.defineProperty(navigator,'connection',{value:{saveData:true,effectiveType:'2g'},configurable:true}));

 // Separate document URL avoids an already fresh A/B entry without clearing any cache.
 fs.copyFileSync(path.join(dRoot,'index.html'),path.join(output,'d-entry.html'));
 await lazyD.goto('http://127.0.0.1:3023/our_story/d-entry.html#photos');await lazyD.reload();await lazyD.getByRole('button',{name:'地图查看',exact:true}).waitFor();
 activateStoredRelease(output,B.id);serving.state.release='B-after-D';const dMap=D.files.find(file=>/assets\/GalleryMap-.*\.js$/.test(file.path));serving.state.missing.add('/'+dMap.path);
 const dFailAt=serving.state.requests.length;await lazyD.getByRole('button',{name:'地图查看',exact:true}).click();await lazyD.getByRole('heading',{name:'地图暂时没有展开'}).waitFor();await lazyD.waitForTimeout(1000);
 check('uncached old D chunk server 404 is bounded',serving.state.requests.slice(dFailAt).some(r=>r.url.includes(dMap.path)&&r.status===404),{requests:serving.state.requests.slice(dFailAt)});
 await lazyD.getByRole('button',{name:'重新加载地图',exact:true}).click();await lazyD.getByRole('heading',{name:'地图暂时没有展开'}).waitFor();check('one manual import retry stays in boundary',true,{});
 // Use the real normal entry for user-triggered recovery, keeping its hash and saved state.
 await lazyD.evaluate(()=>history.replaceState(null,'','/our_story/index.html#photos'));
 await lazyD.getByRole('button',{name:'重新加载地图',exact:true}).click();await lazyD.locator('.gallery-map-province').first().waitFor();check('second manual retry restores into B without reload loop',await lazyD.locator('.gallery-map-province').count()===34,{url:lazyD.url()});serving.state.missing.clear();
 const expiredAt=serving.state.requests.length;
 await lazyD.evaluate(()=>{window.actualNow=Date.now;Date.now=()=>window.actualNow()+61000;});
 await lazyD.waitForTimeout(2300);await lazyD.goto('http://127.0.0.1:3023/away');await lazyD.evaluate(()=>history.back());await lazyD.waitForTimeout(1500);
 check('decoded reuse expiry resumes normal HTTP conditional cache',serving.state.requests.slice(expiredAt).some(r=>r.tile&&r.status===304),{applicationClock:'injected +61s only for decoded age; HTTP TTL expired in real elapsed time',requests:serving.state.requests.slice(expiredAt).filter(r=>r.tile)});
 await lazyD.evaluate(()=>{Date.now=window.actualNow;});
 evidence.serverRequests=serving.state.requests;evidence.profile='persistent .release-qa/g1-profile (no cache clear)';evidence.passed=evidence.checks.every(c=>c.passed);
}catch(error){evidence.fatal=error.stack;console.error(error);}finally{fs.writeFileSync(path.join(dir,'g1.json'),JSON.stringify(evidence,null,2));await context?.close();await serving.close();}console.log(JSON.stringify(evidence.checks.map(c=>({name:c.name,passed:c.passed}))));if(evidence.fatal||!evidence.passed)process.exitCode=1;
