/**
 * 文案与资源路径。图片放入 assets/images/ 对应文件名即可替换。
 * 生图提示词见 docs/image-prompts.md
 */
const ASSETS = {
  bgOpening: 'image/bg-opening.jpg',
  bgWalk: 'image/bg-walk.jpg',
  bgSnack: 'image/bg-walk.jpg',
  bgFlowers: 'image/bg-opening.jpg',
  bgEnding: 'image/bg-opening.jpg',
  pleadBeg: 'image/plead-beg.jpg',
  giftCurtain: 'image/gift-curtain.jpg',
  walkHolding: 'image/walk-holding-hands.png',
  walkNotHolding: 'image/walk-not-holding-hands.jpg',
  flower: 'image/flower-preserved.png',
  travelPhoto1: 'image/travel-photo-1.jpg',
  travelPhoto2: 'image/travel-photo-2.jpg',
  firstMeetSparkler: 'image/first-meet-sparkler.jpg',
  bgm: 'bgm/粉雾海.mp3',
};

const NODES = {
  opening: {
    id: 'opening',
    type: 'opening',
    bg: 'opening',
    prompt: '又是想你的一天，你想我了吗',
  },
  bridge: {
    id: 'bridge',
    type: 'tap',
    bg: 'opening',
    prompt: '好耶，就当作我们待在一块',
    sub: '虽然隔着点距离，但没关系',
    next: 'walk',
  },
  walk: {
    id: 'walk',
    type: 'choice',
    bg: 'walk',
    prompt: '邀请我美丽的平平女士，\n一起线上散步吧',
    choices: [
      {
        label: '好啊',
        value: 'hao',
        feedback: '嘿嘿我就不给你拒绝的机会了',
        next: 'photo1',
        yes: true,
      },
      {
        label: '没问题',
        value: 'ok',
        feedback: '嘿嘿我就不给你拒绝的机会了',
        next: 'photo1',
        yes: true,
      },
    ],
  },
  photo1: {
    id: 'photo1',
    type: 'travel-photo',
    bg: 'walk',
    prompt: '线上散步，也得有点小风景',
    caption: '这是上次去半山森林公园看到的路牌',
    image: ASSETS.travelPhoto1,
    placeholder: '放入 travel-photo-1.jpg（路牌等）',
    button: '往前走',
    next: 'photo2',
  },
  photo2: {
    id: 'photo2',
    type: 'travel-photo',
    bg: 'walk',
    prompt: '这是宁波老外滩的小巷子里拍的',
    caption: '都是想发却没发的日常呢',
    image: ASSETS.travelPhoto2,
    placeholder: '放入 travel-photo-2.jpg',
    button: '继续走',
    next: 'photo3',
  },
  photo3: {
    id: 'photo3',
    type: 'travel-photo',
    bg: 'walk',
    prompt: '还记得我们第一次见面',
    caption: '那天我们一起放仙女棒',
    image: ASSETS.firstMeetSparkler,
    placeholder: '放入 first-meet-sparkler.jpg（仙女棒）',
    button: '继续走',
    next: 'hand',
  },
  hand: {
    id: 'hand',
    type: 'hand',
    bg: 'walk',
    prompt: '我想牵牵你的手，可以吗？',
    choices: [
      { label: '好', value: 'yes' },
      { label: '不好', value: 'no' },
    ],
    next: 'walkVisual',
  },
  walkVisual: {
    id: 'walkVisual',
    type: 'walk-image',
    bg: 'walk',
    captionHold: '那我可不会松手啦！',
    captionNoHold: '好吧，但我下次还问',
    next: 'snack',
  },
  snack: {
    id: 'snack',
    type: 'choice',
    bg: 'snack',
    prompt: '走累了吧？夜宵去吃瘦肉丸吧',
    choices: [
      { label: '吃！', value: 'eat', feedback: '还差一份香酥鸡，下次要补上哦', next: 'giftCurtain', yes: true },
      {
        label: '要吃火鸡面',
        value: 'full',
        feedback: '那只能吃两口哦，剩下的都是我的了',
        next: 'giftCurtain',
      },
    ],
  },
  giftCurtain: {
    id: 'giftCurtain',
    type: 'travel-photo',
    bg: 'opening',
    prompt: '夜宵吃完啦，\n该回家看看了',
    caption: '拉开窗帘，礼物就在窗帘后面等着你',
    image: ASSETS.giftCurtain,
    placeholder: '放入 gift-curtain.jpg（窗帘后的礼物）',
    button: '拉开窗帘',
    next: 'flowers',
  },
  flowers: {
    id: 'flowers',
    type: 'flowers',
    bg: 'flowers',
    lines: [
      '虽然不能亲手送你一束花，但我偷偷准备了一个小礼物。',
      '不过你已经发现了，准备的有点仓促，希望你可以喜欢。',
      '里面是永生花，希望我和它都可以陪你很久很久。',
    ],
    button: '收下',
    next: 'ending',
  },
  ending: {
    id: 'ending',
    type: 'ending',
    bg: 'ending',
    title: '520 快乐',
    lines: [
      '谢谢你愿意陪我胡闹，完成这场线上散步',
      '愿你永远做自己，闪闪发光。',
      '愿你平安顺遂，万事胜意。',
      '也希望以后的每一天，',
      '我都可以 陪在你身边。',
    ],
    closingLine: '一会儿我们语音吧！',
  },
};
