// Generated by scripts/import-gallery-collections.py. Explicit publication approval required by SCOPE; published import.
import { resolvePublicAssetUrl } from '@/shared/config/siteConfig';
import type { Album, MediaAsset } from '@/domain/content';

const LOCAL_ASSETS = [
  {
    "id": "photo-disney-1000013442",
    "slug": "disney",
    "fileName": "1000013442.jpg",
    "width": 960,
    "height": 1280,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013443",
    "slug": "disney",
    "fileName": "1000013443.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013444",
    "slug": "disney",
    "fileName": "1000013444.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013445",
    "slug": "disney",
    "fileName": "1000013445.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013448",
    "slug": "disney",
    "fileName": "1000013448.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013449",
    "slug": "disney",
    "fileName": "1000013449.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013686",
    "slug": "disney",
    "fileName": "1000013686.jpg",
    "width": 1270,
    "height": 1696,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013687",
    "slug": "disney",
    "fileName": "1000013687.jpg",
    "width": 1280,
    "height": 1707,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013688",
    "slug": "disney",
    "fileName": "1000013688.jpg",
    "width": 1270,
    "height": 1696,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013690",
    "slug": "disney",
    "fileName": "1000013690.jpg",
    "width": 2316,
    "height": 5173,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013696",
    "slug": "disney",
    "fileName": "1000013696.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013697",
    "slug": "disney",
    "fileName": "1000013697.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013698",
    "slug": "disney",
    "fileName": "1000013698.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013699",
    "slug": "disney",
    "fileName": "1000013699.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013700",
    "slug": "disney",
    "fileName": "1000013700.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013701",
    "slug": "disney",
    "fileName": "1000013701.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013702",
    "slug": "disney",
    "fileName": "1000013702.jpg",
    "width": 5712,
    "height": 4284,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013703",
    "slug": "disney",
    "fileName": "1000013703.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013704",
    "slug": "disney",
    "fileName": "1000013704.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013705",
    "slug": "disney",
    "fileName": "1000013705.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013706",
    "slug": "disney",
    "fileName": "1000013706.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013707",
    "slug": "disney",
    "fileName": "1000013707.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013708",
    "slug": "disney",
    "fileName": "1000013708.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013709",
    "slug": "disney",
    "fileName": "1000013709.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013710",
    "slug": "disney",
    "fileName": "1000013710.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013711",
    "slug": "disney",
    "fileName": "1000013711.jpg",
    "width": 1280,
    "height": 1707,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013712",
    "slug": "disney",
    "fileName": "1000013712.jpg",
    "width": 1280,
    "height": 1707,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013713",
    "slug": "disney",
    "fileName": "1000013713.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013714",
    "slug": "disney",
    "fileName": "1000013714.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013715",
    "slug": "disney",
    "fileName": "1000013715.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013716",
    "slug": "disney",
    "fileName": "1000013716.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013718",
    "slug": "disney",
    "fileName": "1000013718.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013719",
    "slug": "disney",
    "fileName": "1000013719.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013720",
    "slug": "disney",
    "fileName": "1000013720.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013721",
    "slug": "disney",
    "fileName": "1000013721.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013722",
    "slug": "disney",
    "fileName": "1000013722.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013723",
    "slug": "disney",
    "fileName": "1000013723.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013724",
    "slug": "disney",
    "fileName": "1000013724.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013725",
    "slug": "disney",
    "fileName": "1000013725.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013726",
    "slug": "disney",
    "fileName": "1000013726.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013727",
    "slug": "disney",
    "fileName": "1000013727.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013728",
    "slug": "disney",
    "fileName": "1000013728.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013729",
    "slug": "disney",
    "fileName": "1000013729.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013730",
    "slug": "disney",
    "fileName": "1000013730.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013731",
    "slug": "disney",
    "fileName": "1000013731.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013732",
    "slug": "disney",
    "fileName": "1000013732.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013733",
    "slug": "disney",
    "fileName": "1000013733.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013734",
    "slug": "disney",
    "fileName": "1000013734.jpg",
    "width": 2316,
    "height": 3088,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013735",
    "slug": "disney",
    "fileName": "1000013735.jpg",
    "width": 1280,
    "height": 1707,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013736",
    "slug": "disney",
    "fileName": "1000013736.jpg",
    "width": 2316,
    "height": 3088,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013737",
    "slug": "disney",
    "fileName": "1000013737.jpg",
    "width": 2316,
    "height": 3088,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013738",
    "slug": "disney",
    "fileName": "1000013738.jpg",
    "width": 2316,
    "height": 3088,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013739",
    "slug": "disney",
    "fileName": "1000013739.jpg",
    "width": 2316,
    "height": 3088,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013740",
    "slug": "disney",
    "fileName": "1000013740.jpg",
    "width": 2316,
    "height": 3088,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013741",
    "slug": "disney",
    "fileName": "1000013741.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013742",
    "slug": "disney",
    "fileName": "1000013742.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013743",
    "slug": "disney",
    "fileName": "1000013743.jpg",
    "width": 1920,
    "height": 1080,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013744",
    "slug": "disney",
    "fileName": "1000013744.jpg",
    "width": 1920,
    "height": 1080,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013747",
    "slug": "disney",
    "fileName": "1000013747.jpg",
    "width": 1920,
    "height": 1080,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013749",
    "slug": "disney",
    "fileName": "1000013749.jpg",
    "width": 1920,
    "height": 1080,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013750",
    "slug": "disney",
    "fileName": "1000013750.jpg",
    "width": 1080,
    "height": 1920,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013751",
    "slug": "disney",
    "fileName": "1000013751.jpg",
    "width": 1272,
    "height": 1698,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013752",
    "slug": "disney",
    "fileName": "1000013752.jpg",
    "width": 2316,
    "height": 5173,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013753",
    "slug": "disney",
    "fileName": "1000013753.jpg",
    "width": 1280,
    "height": 1707,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013754",
    "slug": "disney",
    "fileName": "1000013754.jpg",
    "width": 2160,
    "height": 3840,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013755",
    "slug": "disney",
    "fileName": "1000013755.jpg",
    "width": 1441,
    "height": 1920,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013756",
    "slug": "disney",
    "fileName": "1000013756.jpg",
    "width": 3840,
    "height": 2160,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013757",
    "slug": "disney",
    "fileName": "1000013757.jpg",
    "width": 3840,
    "height": 2160,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013758",
    "slug": "disney",
    "fileName": "1000013758.jpg",
    "width": 3840,
    "height": 2160,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013760",
    "slug": "disney",
    "fileName": "1000013760.jpg",
    "width": 3840,
    "height": 2160,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013761",
    "slug": "disney",
    "fileName": "1000013761.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-disney-1000013762",
    "slug": "disney",
    "fileName": "1000013762.jpg",
    "width": 2316,
    "height": 3088,
    "alt": "迪士尼照片"
  },
  {
    "id": "photo-confession-2026-06-26",
    "slug": "confession",
    "fileName": "2026-06-26.jpg",
    "width": 3443,
    "height": 4591,
    "alt": "告白照片"
  },
  {
    "id": "photo-festivals-2026-05-20",
    "slug": "festivals",
    "fileName": "2026-05-20.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "节日照片"
  },
  {
    "id": "photo-festivals-七夕",
    "slug": "festivals",
    "fileName": "%E4%B8%83%E5%A4%95.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "节日照片"
  },
  {
    "id": "photo-lingyin-2026-03-14",
    "slug": "lingyin",
    "fileName": "2026-03-14.jpg",
    "width": 3213,
    "height": 5712,
    "alt": "灵隐寺照片"
  },
  {
    "id": "photo-daily-1000013410",
    "slug": "daily",
    "fileName": "1000013410.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013411",
    "slug": "daily",
    "fileName": "1000013411.jpg",
    "width": 5712,
    "height": 4284,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013412",
    "slug": "daily",
    "fileName": "1000013412.jpg",
    "width": 5712,
    "height": 4284,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013413",
    "slug": "daily",
    "fileName": "1000013413.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013415",
    "slug": "daily",
    "fileName": "1000013415.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013416",
    "slug": "daily",
    "fileName": "1000013416.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013417",
    "slug": "daily",
    "fileName": "1000013417.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013418",
    "slug": "daily",
    "fileName": "1000013418.jpg",
    "width": 4284,
    "height": 5712,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013419",
    "slug": "daily",
    "fileName": "1000013419.jpg",
    "width": 3024,
    "height": 4032,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013424",
    "slug": "daily",
    "fileName": "1000013424.jpg",
    "width": 4096,
    "height": 3072,
    "alt": "日常照片"
  },
  {
    "id": "photo-daily-1000013425",
    "slug": "daily",
    "fileName": "1000013425.jpg",
    "width": 1279,
    "height": 2275,
    "alt": "日常照片"
  }
];
export const GALLERY_MEDIA_ASSETS: readonly MediaAsset[] = Object.freeze(LOCAL_ASSETS.map(item => {
  const thumb = resolvePublicAssetUrl(`gallery/collections/${item.slug}/${item.fileName}`);
  return Object.freeze({ id: item.id, spaceId: 'local-our-story', kind: 'image' as const,
    url: thumb, alt: item.alt, width: item.width, height: item.height, mimeType: 'image/jpeg',
    loadingRole: 'interaction' as const, variants: { thumb,
      original: resolvePublicAssetUrl(`gallery/originals/${item.slug}/${item.fileName}`) } });
}));
export const GALLERY_LOCAL_ALBUMS: readonly Album[] = Object.freeze([
  {
    "id": "album-disney",
    "spaceId": "local-our-story",
    "sortOrder": 0,
    "visibility": "public",
    "title": "迪士尼",
    "location": "上海迪士尼",
    "coverMediaAssetId": "photo-disney-1000013716",
    "mediaAssetIds": [
      "photo-disney-1000013442",
      "photo-disney-1000013443",
      "photo-disney-1000013444",
      "photo-disney-1000013445",
      "photo-disney-1000013448",
      "photo-disney-1000013449",
      "photo-disney-1000013686",
      "photo-disney-1000013687",
      "photo-disney-1000013688",
      "photo-disney-1000013690",
      "photo-disney-1000013696",
      "photo-disney-1000013697",
      "photo-disney-1000013698",
      "photo-disney-1000013699",
      "photo-disney-1000013700",
      "photo-disney-1000013701",
      "photo-disney-1000013702",
      "photo-disney-1000013703",
      "photo-disney-1000013704",
      "photo-disney-1000013705",
      "photo-disney-1000013706",
      "photo-disney-1000013707",
      "photo-disney-1000013708",
      "photo-disney-1000013709",
      "photo-disney-1000013710",
      "photo-disney-1000013711",
      "photo-disney-1000013712",
      "photo-disney-1000013713",
      "photo-disney-1000013714",
      "photo-disney-1000013715",
      "photo-disney-1000013716",
      "photo-disney-1000013718",
      "photo-disney-1000013719",
      "photo-disney-1000013720",
      "photo-disney-1000013721",
      "photo-disney-1000013722",
      "photo-disney-1000013723",
      "photo-disney-1000013724",
      "photo-disney-1000013725",
      "photo-disney-1000013726",
      "photo-disney-1000013727",
      "photo-disney-1000013728",
      "photo-disney-1000013729",
      "photo-disney-1000013730",
      "photo-disney-1000013731",
      "photo-disney-1000013732",
      "photo-disney-1000013733",
      "photo-disney-1000013734",
      "photo-disney-1000013735",
      "photo-disney-1000013736",
      "photo-disney-1000013737",
      "photo-disney-1000013738",
      "photo-disney-1000013739",
      "photo-disney-1000013740",
      "photo-disney-1000013741",
      "photo-disney-1000013742",
      "photo-disney-1000013743",
      "photo-disney-1000013744",
      "photo-disney-1000013747",
      "photo-disney-1000013749",
      "photo-disney-1000013750",
      "photo-disney-1000013751",
      "photo-disney-1000013752",
      "photo-disney-1000013753",
      "photo-disney-1000013754",
      "photo-disney-1000013755",
      "photo-disney-1000013756",
      "photo-disney-1000013757",
      "photo-disney-1000013758",
      "photo-disney-1000013760",
      "photo-disney-1000013761",
      "photo-disney-1000013762"
    ],
    "mapPoint": {
      "x": 0,
      "y": 0,
      "label": "上海",
      "city": "上海",
      "precision": "city"
    },
    "startDate": "2026-09-13",
    "endDate": "2026-09-13",
    "datePrecision": "day"
  },
  {
    "id": "album-confession",
    "spaceId": "local-our-story",
    "sortOrder": 1,
    "visibility": "public",
    "title": "告白",
    "location": "青田温溪镇温中路81号",
    "coverMediaAssetId": "photo-confession-2026-06-26",
    "mediaAssetIds": [
      "photo-confession-2026-06-26"
    ],
    "mapPoint": {
      "x": 0,
      "y": 0,
      "label": "浙江",
      "city": "丽水",
      "precision": "city"
    },
    "startDate": "2026-06-26",
    "endDate": "2026-06-26",
    "datePrecision": "day"
  },
  {
    "id": "album-festivals",
    "spaceId": "local-our-story",
    "sortOrder": 2,
    "visibility": "public",
    "title": "节日",
    "location": "丽水市莲都区南明山街道丽沙小区",
    "coverMediaAssetId": "photo-festivals-七夕",
    "mediaAssetIds": [
      "photo-festivals-2026-05-20",
      "photo-festivals-七夕"
    ],
    "mapPoint": {
      "x": 0,
      "y": 0,
      "label": "浙江",
      "city": "丽水",
      "precision": "city"
    }
  },
  {
    "id": "album-lingyin",
    "spaceId": "local-our-story",
    "sortOrder": 3,
    "visibility": "public",
    "title": "灵隐寺",
    "location": "杭州灵隐寺",
    "coverMediaAssetId": "photo-lingyin-2026-03-14",
    "mediaAssetIds": [
      "photo-lingyin-2026-03-14"
    ],
    "mapPoint": {
      "x": 0,
      "y": 0,
      "label": "浙江",
      "city": "杭州",
      "precision": "city"
    },
    "startDate": "2026-03-14",
    "endDate": "2026-03-14",
    "datePrecision": "day"
  },
  {
    "id": "album-daily",
    "spaceId": "local-our-story",
    "sortOrder": 4,
    "visibility": "public",
    "title": "日常",
    "location": "丽水市莲都区南明山街道丽沙小区",
    "coverMediaAssetId": "photo-daily-1000013424",
    "mediaAssetIds": [
      "photo-daily-1000013410",
      "photo-daily-1000013411",
      "photo-daily-1000013412",
      "photo-daily-1000013413",
      "photo-daily-1000013415",
      "photo-daily-1000013416",
      "photo-daily-1000013417",
      "photo-daily-1000013418",
      "photo-daily-1000013419",
      "photo-daily-1000013424",
      "photo-daily-1000013425"
    ],
    "mapPoint": {
      "x": 0,
      "y": 0,
      "label": "浙江",
      "city": "丽水",
      "precision": "city"
    }
  }
] as Album[]);
export const GALLERY_PUBLIC_ALBUMS: readonly Album[] = GALLERY_LOCAL_ALBUMS;
